### ISSUE TITLE
Bug in capture

### ISSUE THREAD

**Issue by anpd03** [paviad/GoSharp#1]
Just wanted to let you know that there looks to be a bug in the capture code. When capturing by playing on a point with no liberties both black and white stones are removed.

**Comment by paviad** [comment]
Thanks will look into it

**Comment by anpd03** [comment]
Example can be seen here. Before blacks move [https://dl.dropboxusercontent.com/u/815495/1.png](url) after [https://dl.dropboxusercontent.com/u/815495/2.png](url)

**Comment by anpd03** [comment]
Example here 

Before blacks move
![1](https://cloud.githubusercontent.com/assets/10407381/18484953/09a7dd1a-79eb-11e6-9bdf-e4240ba3854a.png)

After
![2](https://cloud.githubusercontent.com/assets/10407381/18484958/12dda00e-79eb-11e6-92bb-81e9b9066ce0.png)
