### ISSUE TITLE
Capture count not correct in all cases

### ISSUE THREAD

**Issue by anpd03** [paviad/GoSharp#11]
Sometime when capturing a large group the stone count is wrong, noticed when captured 14 stones. Had 8 captured, the variable said I had captured 31 not 22.

**Comment by paviad** [comment]
Can you please provide a reproducible example?

**Comment by anpd03** [comment]
In this case it counts as 14 captured https://www.dropbox.com/s/uf5b50e8bs5lzh8/capture.png?dl=0
Might be when it's two separate groups captured at the same time.

**Comment by paviad** [comment]
You're right, can't believe this bug has been around for so long :)

**Comment by anpd03** [comment]
Thanks!
