### ISSUE TITLE
Question about sgf support

### ISSUE THREAD

**Issue by anpd03** [paviad/GoSharp#2]
Been using the sgf loader to succesfully load both tsumego files and pro-games.  Are any of the tags  saved somewhere such as player names, result etc? Also node comments with specific intersections that should be marked?

Thanks for the great work on this. Really usefull!

**Comment by nerai** [comment]
@anpd03 I've created PR #4 that addresses some of your issues.

**Comment by anpd03** [comment]
Cheers, will merge with my code and take a look.

**Comment by paviad** [comment]
resolved by pull request #4
