### ISSUE TITLE
what's difference Go and GoSharpCore?

### ISSUE THREAD

**Issue by kanitabe** [paviad/GoSharp#31]
Thank you for creating such a wonderful library.
The code in the root directory (namespace go) and the code in the GoSharpCore directory (namespace GoSharpCore) are similar and almost identical.
What is the difference between them and how should I use them depending on the situation?

**Comment by paviad** [comment]
Hi, my pleasure :)

The `GoSharpCore` folder contains the library built for *.NET Standard 2.0* that might be referenced by all versions of .NET Framework and .NET Core.

The code outside that folder is the original code I wrote for .NET Framework (before .NET Core was conceived)

**Comment by kanitabe** [comment]
Thanks for the answer.

So you are saying that GoSharpCore is newer and in the current situation I should use GoSharpCore?
By the way, I'm thinking of using it within Unity.

**Comment by paviad** [comment]
Yes, use the `GoSharpCore` code it is more future proof :)
