### ISSUE TITLE
SerializeToSGF may not be working properly

### ISSUE THREAD

**Issue by kanitabe** [paviad/GoSharp#33]
This Issue was closed, so I am reposting here.
For more information, please click here.
https://github.com/paviad/GoSharp/issues/32#issuecomment-1279289934

As the title suggests, it is probably not working correctly and I would appreciate it if you could check.

**Comment by paviad** [comment]
Alright I had to refresh my memory, but the code is working as designed. The thing is, you must always serialize the initial game object, not the intermediate ones. This way you get all variations from the beginning serialized properly:

```c#
GameInfo gi = new GameInfo() { Handicap = 0, StartingPlayer = Content.Black, Komi = 6.5 };
Game gameInitial = new Game(gi);
Game game;
bool legal;

game = gameInitial;
var result = gameInitial.SerializeToSGF(null); // (;KM[6.50]SZ[19])

game = game.MakeMove(3, 3, out legal);
var result2 = gameInitial.SerializeToSGF(null); // (;KM[6.50]SZ[19];B[dd])

game = game.MakeMove(16, 16, out legal);
var result3 = gameInitial.SerializeToSGF(null); // (;KM[6.50]SZ[19];B[dd];W[qq])
```
