### ISSUE TITLE
Request, Disable Illegal Move

### ISSUE THREAD

**Issue by kanitabe** [paviad/GoSharp#37]
Hi,  We continue to use GoSharp.

If a MakeMoves is illegal, I would like a method that can safely undo it ,
or a method that doesn't record the move in the first place if it's illegal.

**Comment by paviad** [comment]
Done, added an optional parameter to `MakeMove` to prevent adding an illegal variation, as well as a `RemoveVariation` method to allow removing an existing variation.

Closed by d8ad09ab00e8cb82360e0417fda148b43b74c9e1

**Comment by kanitabe** [comment]
Wow, Thank you for the very quick update!
